export const NAME_LABEL = "Название столбика"
export const BG_LABEL = "Задний фон"
export const DEFAULT_BG_VALUE = "#31BEB2"
export const SUBMIT_FORM_TEXT = "Подтвердить"
export const DELETE_COLUMN_QUESTION = "Вы точно хотите удалить данную колону?"
