export const CREATE_TAG_OFFER = "Добавить задачу"
export const CREATE_TASK_PLACEHOLDER = "Название задачи"
export const TASK_OPTION_EDIT_ITEM = "Редактировать"
export const TASK_OPTION_NAME_LABEL = "Название задачи"
export const TASK_OPTION_DESCRIPTION_LABEL = "Описание"
export const TASK_OPTION_DELETE_ITEM = "Удалить"
export const TASK_DELETE_QUESTION = "Вы точно хотите удалить задачу?"
